### PR TITLE
Introdev

### PR DESCRIPTION
**Pull request by maidenone**
lets see if someone wants to change anything before we publish, maybe change date?

### CODE REVIEW

**Comment by luzpaz** [comment]
@maidenone should we mention anything about: 
* needing help packaging freecad on different distros
* helping to keep 3rd party libs that FC needs up to date on different distros

And pointing them to https://github.com/luzpaz/FreeCAD-dependencies/ ?

**Comment by maidenone** [comment]
Feel free to add that ;)

**Comment by luzpaz** [comment]
@maidenone Lets just create another post dedicated to packaging and just go ahead and ship this one?

**Comment by maidenone** [comment]
do it

**Comment by luzpaz** [comment]
@kkremitzki please merge

**Comment by kkremitzki** [comment]
Post is now available at https://freecad.github.io/posts/introduction-to-freecad-development/

**Pull request merged**
